# Release-build ProGuard / R8 keep rules for substreamer-rn.
#
# Loaded by app.config.js and injected via expo-build-properties as
# `android.extraProguardRules` at prebuild time. Editing here is the
# source of truth — DO NOT edit android/app/proguard-rules.pro directly
# (it's regenerated by `expo prebuild`).
#
# Drift protection: `scripts/validate-proguard-rules.js` enforces the
# presence of the critical keep rules below. Run via `npm run validate:proguard`.

# Expo native modules (incl. expo-modules-core reflection paths)
-keep class expo.modules.** { *; }

# Media3 / ExoPlayer — the playback engine behind react-native-queue-player.
# Stripping these is the most common cause of release-only crashes when audio
# playback starts.
-keep class androidx.media3.** { *; }
-keep interface androidx.media3.** { *; }
-dontwarn androidx.media3.**

# OkHttp / Okio — RN networking + Media3 DataSource
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keep class okio.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**

# React Native networking classes accessed reflectively from SslTrustStore.kt
# via Class.forName("com.facebook.react.modules.network.OkHttpClientProvider")
-keep class com.facebook.react.modules.network.OkHttpClientProvider { *; }
-keep class com.facebook.react.modules.network.OkHttpClientFactory { *; }
-keep interface com.facebook.react.modules.network.OkHttpClientFactory { *; }
-keep class com.facebook.react.modules.network.** { *; }

# Hermes — referenced by JSI bridge during init
-keep class com.facebook.hermes.** { *; }
-dontwarn com.facebook.hermes.**

# Kotlin metadata — required for reflective field/method access in some libs
-keep class kotlin.Metadata { *; }
-keepclassmembers class **$WhenMappings { <fields>; }
-keepclassmembers class kotlin.coroutines.SafeContinuation { volatile <fields>; }

# JSSE / SSL — keep our custom TrustManager wiring (expo-ssl-trust module)
-keep class * implements javax.net.ssl.X509TrustManager { *; }
-keep class * implements javax.net.ssl.HostnameVerifier { *; }

# SoLoader
-keep class com.facebook.soloader.** { *; }
-dontwarn com.facebook.soloader.**

# React Native feature flags
-keep class com.facebook.react.internal.featureflags.** { *; }

# Margelo Nitro Modules / Queue Player
-keep class com.margelo.nitro.** { *; }
-dontwarn com.margelo.nitro.**

# Crash-report readability. AGP's common config keeps annotations and Signature but NOT
# line numbers, and R8 optimization inlines frames — without these, a Play Console stack
# trace de-obfuscates to names with no lines, which is not enough to act on.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
